nome : tempo_template
descrição : Um novo projeto Flutter.

publish_to : ' none '  # Remova esta linha se você deseja publicar em pub.dev

versão : 1.0.0+1

ambiente :
  SDK : ' >=2.17.2 <3.0.0 '

dependências :
  vibração :
    sdk : vibração

  cupertino_icons : ^1.0.2
  geolocalizador : ^9.0.2
  http : ^0.13.5
  flutter_spinkit : ^5.1.0

dev_dependencies :
  flutter_test :
    sdk : vibração

  flutter_lints : ^2.0.0

vibração :
  usa-material-design : true

  ativos :
    - imagens/

  fontes :
    - família : Spartan MB
      fontes :
        - ativo : fonts/SpartanMB-Black.otf
          peso : 900